### ISSUE TITLE
Refactor batch data access into own class or function

### ISSUE THREAD

**Issue by mstockerl** [DigitalProductschool/website#140]
At the moment, we have mixed up Data fetching with rendering the data. Therefore, we can't reuse the data fetching logic and we duplicate this logic. 
In addition to that, we are not able to test this functionality in the future. 

So far, we have the same logic in [application form](https://github.com/DigitalProductschool/website/blob/1e96e3f271a4e6dce6aed809886def88f1abcc8d/src/components/application/form/_index.jsx#L188) and [batch details](https://github.com/DigitalProductschool/website/blob/1e96e3f271a4e6dce6aed809886def88f1abcc8d/src/components/shared/batch-details/index.tsx#L108). 

The code to access the Firestore database should be refactored in a separate class/function and this new function should be used instead.

**Comment by bhawna333** [comment]
If no one is working on this at the moment, then I'd like to take over this :)

**Comment by mstockerl** [comment]
There is already something done here. :) 

https://github.com/DigitalProductschool/website/tree/refactorBatchDetails

**Comment by mstockerl** [comment]
@danielbedo Can we merge the changes in staging at least?

**Comment by bsinoimeri** [comment]
I think this was not merged :) As i am making some changes in the batch details i will merge it now :)
