### ISSUE TITLE
Change text of the application form on the IxD Track

### ISSUE THREAD

**Issue by danielbedo** [DigitalProductschool/website#162]
We want to see examples of work the applicants did so please change the text in the application form (only for IxD) accordingly:
"Please make sure that either your CV or your cover letter contains examples of your work in the field of interaction design, UI/UX design or user-centered design. You can either provide a link or add additional pages in your PDF."
<img width="778" alt="Bildschirmfoto 2020-02-17 um 13 26 30" src="https://user-images.githubusercontent.com/813134/74653981-99bea900-5189-11ea-8e7c-3d4694755ff9.png">

**Comment by bsinoimeri** [comment]
Done. Its commited in the staging branch. Also added on website trello board. Basti can test the changes and then i can commit to master.
