### ISSUE TITLE
Add linter or code formatter

### ISSUE THREAD

**Issue by lustoykov** [DigitalProductschool/website#27]

**Comment by ramitsurana** [comment]
Can you please elaborate which tool are you looking forward to use?

**Comment by lustoykov** [comment]
I was thinking about https://prettier.io

**Comment by ramitsurana** [comment]
OKay. Do you guys have a Jenkins pipeline with automated checks for such kind of tools?

**Comment by lustoykov** [comment]
Yes, but I was thinking about adding it as a precommit hook

**Comment by lustoykov** [comment]
comin soon

**Comment by mstockerl** [comment]
I was wondering, whether we can include it into the deployment 🤔

**Comment by ramitsurana** [comment]
> I was wondering, whether we can include it into the deployment 🤔

Maybe as a pre-requisite test check whether everything is working fine or not.

**Comment by ramitsurana** [comment]
@lustoykov Can you share an small example where https://prettier.io/  is used with the precommit hook settings? I think I might be able to play around with it using it as a reference.

**Comment by lustoykov** [comment]
@ramitsurana do you want to try that now with the current setup? 

Here is an example, [Line#19](https://github.com/parcel-bundler/parcel/blob/master/package.json#L19) + [Line#31](https://github.com/parcel-bundler/parcel/blob/master/package.json#L31)

**Comment by ramitsurana** [comment]
Thanks @lustoykov . Yes

**Comment by lustoykov** [comment]
This has been done
