### ISSUE TITLE
Links Exp.Partners _blank

### ISSUE THREAD

**Issue by BastianRieder** [DigitalProductschool/website#28]
Bitte die Links auf den Logos der Experience Partners auf _blank setzen, so dass sie nicht im Fenster unserer Webseite aufgehen.

**Comment by steffenk71** [comment]
We should not alter the default link behaviour. The user should be in control. https://medium.com/the-metric/links-should-open-in-the-same-window-447da3ae59ba

**Comment by BastianRieder** [comment]
From a marketing point of view opening links in the same video is the worst thin you can do:
1.) you lead the people away from your site and they will never come back and convert (or you have to spend extra money to bring them back)
2.) You increase the bounce rate => very bad for SEO

And also the usability experts are discussing this topic, because the majority of the sites out there prefer opening in a new window and the users are used to it. No one of the normal users know the keys how to open a new window and then are frustrated because it's hard for them to find the beginning of their journey.

And even most usability experts hate it when links open in the same window (read the comments):
https://growth.org/discuss/external-links-open-them-in-a-new-tab-or-in-the-same-tab-why-any-data:

**Comment by steffenk71** [comment]
https://www.media-affin.de/gruende-gegen-target-blank

**Comment by BastianRieder** [comment]
Ja, aber der User hasst es, wenn externe Links in einem neuen Fenster aufgehen! In Internet-Urzeiten, als es noch keine Tabs gab, mag es ok gewesen sein, aber heute mit TABs ist es nur noch verwirrend. Und für jeden Link, den du schickst, finde ich einen gegen-Link ;-)
http://uxmovement.com/navigation/why-external-links-should-open-in-new-tabs/
