### ISSUE TITLE
Redirect to /index does not work with query parameter 

### ISSUE THREAD

**Issue by mstockerl** [DigitalProductschool/website#30]
https://digitalproductschool.io?hey=test should redirect to https://digitalproductschool.io/index?hey=test

**Comment by mstockerl** [comment]
@lustoykov I imagine this issue is obsolete after the move to Gatsby, isn't it?

**Comment by lustoykov** [comment]
👍  Waiting for the official release before we close all of them 😈 😈

**Comment by lustoykov** [comment]
Legacy as of Gatsby rework
