### ISSUE TITLE
Link images to apply page

### ISSUE THREAD

**Issue by lustoykov** [DigitalProductschool/website#36]
Currently, explicit click of the apply button is needed to visit the application page. We want to link the images too, so that click there takes the user to the application page as well.
<img width="1369" alt="screenshot 2018-10-23 at 10 27 14" src="https://user-images.githubusercontent.com/20355307/47346850-51cf6500-d6ae-11e8-9fc8-4cacb47c9753.png">

**Comment by pranjal2394** [comment]
I can look into this

**Comment by lustoykov** [comment]
It's yours! ;-)

**Comment by lustoykov** [comment]
Hello @pranjal2394 as you have seen, only the white squares are linked and not the whole image. Would you like to try fix it?

**Comment by mstockerl** [comment]
@lustoykov This issue is fixed, isn't it?
