### ISSUE TITLE
Add dates to "Pick your track"

### ISSUE THREAD

**Issue by lustoykov** [DigitalProductschool/website#38]
Extend the frontend to match the design below (dates added to pick your track - in bold)
<img width="754" alt="screenshot 2018-10-23 at 12 43 46" src="https://user-images.githubusercontent.com/20355307/47355325-5fdab100-d6c1-11e8-914f-7a727521e424.png">

**Comment by ankita-sri** [comment]
I could take care of this :D

**Comment by ankita-sri** [comment]
I could take care of this :D

**Comment by lustoykov** [comment]
it's yours! ;-)

**Comment by BastianRieder** [comment]
Here you can copy the text:

There are three batches per year, usually starting in January, May, and September. The application process is ongoing. 
Currently, you can apply for the following batches:
- Batch #6: January 7 to March 29, 2019
