### ISSUE TITLE
Change text on EXPAND YOUR NETWORK

### ISSUE THREAD

**Issue by lustoykov** [DigitalProductschool/website#39]
Please match the design below (only text changes)

<img width="559" alt="screenshot 2018-10-23 at 12 46 54" src="https://user-images.githubusercontent.com/20355307/47355478-bd6efd80-d6c1-11e8-895e-e59a922580f2.png">

**Comment by pranjal2394** [comment]
Can look into this

**Comment by lustoykov** [comment]
it's yours! ;-)

**Comment by BastianRieder** [comment]
Here you can copy the text:

Visit the various other programs of UnternehmerTUM, take part in our or other meetups and get in touch with Munich's start-up and tech scene.
