### ISSUE TITLE
Change text on OUR PROGRAM

### ISSUE THREAD

**Issue by lustoykov** [DigitalProductschool/website#40]
Please match the design below (only text changes)

<img width="503" alt="screenshot 2018-10-23 at 12 47 39" src="https://user-images.githubusercontent.com/20355307/47355518-d8da0880-d6c1-11e8-90b6-7aa7324ca5b7.png">

**Comment by bhawna333** [comment]
I'd like to see into this.

**Comment by lustoykov** [comment]
It's yours! ;-)

**Comment by BastianRieder** [comment]
Here you can copy the new text:

Be part of a unique 3-month full-time training program by UnternehmerTUM, Europe's biggest Entrepreneurship Center. There are three batches per year, usually starting in January, May, and September.
