### ISSUE TITLE
Setup Cloud Build pipeline for cloudfunction

### ISSUE THREAD

**Issue by mstockerl** [DigitalProductschool/website#88]
Deployment to 
- Staging from staging branch
- Production from master branch

**Comment by mstockerl** [comment]
@bhawna333 This is already done, isn't it?

**Comment by bhawna333** [comment]
I don't remember really. I guess not. I don't remember doing it. I'll have a look and let you know

**Comment by bhawna333** [comment]
Yup i think this is done. There was other issue related to it to deploy firebase functions #129 , I just created the pull request for it

**Comment by mstockerl** [comment]
Ok. I close it.
